### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by jocelynthode** [mittwald/kube-mail#89]
Hey @martin-helmich,

Would it be possible to create a new release including the latest changes done here: https://github.com/mittwald/kube-mail/commit/9ebbe1d982289c0d72b000f6f4c5c1ac8295e046 ?

This would allow me to rely on the upstream chart instead of vendoring it in my repo as I currently do :)

**Comment by elenz97** [comment]
Hey @jocelynthode, the changes you're looking for are now in [`v0.10.0`](https://github.com/mittwald/kube-mail/releases/tag/v0.10.0) and subsequent `[releases](https://github.com/mittwald/kube-mail/releases)`.

**Comment by jocelynthode** [comment]
Thanks works as expected!
